import 'package:flutter/material.dart';

const _bg = Color(0xFFF7F0E3);
const _card = Color(0xFFFFF9EF);
const _muted = Color(0xFFEFE3D0);
const _fg = Color(0xFF3A2925);
const _dim = Color(0xFF765F55);
const _primary = Color(0xFF238F89);
const _accent = Color(0xFFC65A3A);
const _purple = Color(0xFF7A3F69);
const _yellow = Color(0xFFD5A62A);
const _border = Color(0xFFD8C5AC);

const _heroImage = 'assets/image/hero.png';
const _aboutImage = 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?q=80&w=1200&auto=format&fit=crop';
const _products = [
  {'name': 'Cesta Trançada Sol', 'artisan': 'Maria', 'price': 'R\$ 85', 'category': 'Casa', 'image': 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=900&auto=format&fit=crop'},
  {'name': 'Colar Raízes', 'artisan': 'Joana', 'price': 'R\$ 120', 'category': 'Joias', 'image': 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?q=80&w=900&auto=format&fit=crop'},
  {'name': 'Boneca Abayomi', 'artisan': 'Ana', 'price': 'R\$ 95', 'category': 'Brinquedos', 'image': 'https://images.unsplash.com/photo-1560932684-4d7e7a1f2f0f?q=80&w=900&auto=format&fit=crop'},
  {'name': 'Bolsa Horizonte', 'artisan': 'Maria', 'price': 'R\$ 160', 'category': 'Acessórios', 'image': 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=900&auto=format&fit=crop'},
  {'name': 'Brinco Semente', 'artisan': 'Lúcia', 'price': 'R\$ 70', 'category': 'Joias', 'image': 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=900&auto=format&fit=crop'},
  {'name': 'Manta Memória', 'artisan': 'Rosa', 'price': 'R\$ 210', 'category': 'Vestuário', 'image': 'https://images.unsplash.com/photo-1604176354204-9268737828e4?q=80&w=900&auto=format&fit=crop'},
];

enum Lang { pt, en, es }
enum Page { home, about, products, login, artisanSignup, accountSignup, buyer, artisan, legal }

enum ArtisanSection { overview, orders, messages, products, sales, export, help, settings }

enum LegalDoc { terms, privacy, cookies, commerce, community }

String tr(Lang l, String pt, String en, String es) => l == Lang.pt ? pt : l == Lang.en ? en : es;

class CurrentHomePage extends StatefulWidget {
  const CurrentHomePage({super.key});
  @override State<CurrentHomePage> createState() => _CurrentHomePageState();
}

class _CurrentHomePageState extends State<CurrentHomePage> {
  Lang lang = Lang.pt;
  Page page = Page.home;
  int cart = 0;
  final favorites = <int>{};
  bool signedIn = false;
  String role = 'buyer';
  ArtisanSection artisanSection = ArtisanSection.overview;
  LegalDoc legalDoc = LegalDoc.terms;
  String category = 'Todos';
  String toast = '';

  void go(Page p) => setState(() { page = p; });
  void addCart() { setState(() => cart++); _snack(tr(lang, 'Produto adicionado ao carrinho.', 'Product added to cart.', 'Producto añadido al carrito.')); }
  void _snack(String text) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(text), behavior: SnackBarBehavior.floating));

  @override
  Widget build(BuildContext context) {
    Widget body;
    switch (page) {
      case Page.home: body = _home(); break;
      case Page.about: body = _about(); break;
      case Page.products: body = _catalog(); break;
      case Page.login: body = _login(); break;
      case Page.artisanSignup: body = _artisanSignup(); break;
      case Page.accountSignup: body = _accountSignup(); break;
      case Page.buyer: body = _buyer(); break;
      case Page.artisan: body = _artisan(); break;
      case Page.legal: body = _legal(); break;
    }
    return Scaffold(
      backgroundColor: _bg,
      body: Column(children: [if (page != Page.artisan) _header(), Expanded(child: AnimatedSwitcher(duration: const Duration(milliseconds: 250), child: KeyedSubtree(key: ValueKey(page), child: body)))]),
      floatingActionButton: page == Page.artisan ? null : FloatingActionButton.small(onPressed: () => _snack(tr(lang, 'Olá! Como podemos ajudar?', 'Hello! How can we help?', '¡Hola! ¿Cómo podemos ayudarte?')), backgroundColor: _primary, foregroundColor: Colors.white, child: const Icon(Icons.chat_bubble_outline)),
    );
  }

  Widget _header() {
    final wide = MediaQuery.sizeOf(context).width > 860;
    final logo = InkWell(onTap: () => go(Page.home), child: Image.asset('assets/image/logo-mulheres-artesas-heliopolis.png', width: 150, height: 70, fit: BoxFit.contain));
    final nav = Row(mainAxisSize: MainAxisSize.min, children: [_nav('Início', Page.home), _nav(tr(lang, 'Quem Somos', 'About Us', 'Quiénes Somos'), Page.about), _nav(tr(lang, 'Produtos', 'Products', 'Productos'), Page.products)]);
    final actions = Row(mainAxisSize: MainAxisSize.min, children: [
      IconButton(onPressed: () => go(Page.login), tooltip: tr(lang, 'Minha conta', 'My account', 'Mi cuenta'), icon: const Icon(Icons.person_outline)),
      Badge(label: Text('$cart'), isLabelVisible: cart > 0, child: IconButton(onPressed: () => go(Page.buyer), tooltip: 'Carrinho', icon: const Icon(Icons.shopping_cart_outlined))),
      _language(),
      if (!wide) PopupMenuButton<String>(onSelected: (v) { if (v == 'home') go(Page.home); if (v == 'about') go(Page.about); if (v == 'products') go(Page.products); }, itemBuilder: (_) => const [PopupMenuItem(value: 'home', child: Text('Início')), PopupMenuItem(value: 'about', child: Text('Quem Somos')), PopupMenuItem(value: 'products', child: Text('Produtos'))], child: const Icon(Icons.menu)),
    ]);
    return Container(
      decoration: const BoxDecoration(color: Color(0xFFFBF5E9), border: Border(bottom: BorderSide(color: _border, width: 1.2))),
      child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1400), child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 10),
        child: SizedBox(height: 70, child: Stack(alignment: Alignment.center, children: [
          Align(alignment: Alignment.centerLeft, child: logo),
          if (wide) Align(alignment: Alignment.center, child: nav),
          Align(alignment: Alignment.centerRight, child: actions),
        ])),
      ))),
    );
  }

  Widget _nav(String label, Page p) => TextButton(onPressed: () => go(p), child: Text(label, style: TextStyle(color: page == p ? _fg : _dim, fontWeight: FontWeight.w700)));

  Widget _language() {
    return PopupMenuButton<Lang>(initialValue: lang, onSelected: (v) => setState(() { lang = v; category = 'Todos'; }), itemBuilder: (_) => const [PopupMenuItem(value: Lang.pt, child: Text('🇧🇷 Português')), PopupMenuItem(value: Lang.en, child: Text('🇺🇸 English')), PopupMenuItem(value: Lang.es, child: Text('🇪🇸 Español'))], child: Container(padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8), decoration: BoxDecoration(border: Border.all(color: _border), borderRadius: BorderRadius.circular(6)), child: Text(lang == Lang.pt ? 'BR PT' : lang == Lang.en ? 'EN' : 'ES')));
  }

  Widget _home() => SingleChildScrollView(child: Column(children: [_hero(), _aboutHome(), _featured(), _how(), _signup(), _footer()]));

  Widget _hero() {
    final desktop = MediaQuery.sizeOf(context).width > 900;
    final copy = tr(lang, 'Uma plataforma feita para conectar você ao artesanato de Heliópolis. Descubra produtos únicos feitos à mão por mulheres artesãs da comunidade, conheça suas histórias e encontre peças com identidade, criatividade e propósito.', 'A platform made to connect you with the crafts of Heliópolis. Discover unique handmade products created by women artisans from the community, learn their stories and find pieces with identity, creativity and purpose.', 'Una plataforma creada para conectarte con la artesanía de Heliópolis. Descubre productos únicos hechos a mano por mujeres artesanas de la comunidad, conoce sus historias y encuentra piezas con identidad, creatividad y propósito.');
    final left = Container(padding: EdgeInsets.symmetric(horizontal: desktop ? 58 : 26, vertical: desktop ? 90 : 55), decoration: const BoxDecoration(gradient: LinearGradient(colors: [_bg, Color(0xFFF1DFC6)])), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [
      Container(padding: const EdgeInsets.symmetric(horizontal: 13, vertical: 8), decoration: BoxDecoration(color: const Color(0xFFE9F1E8), border: Border.all(color: const Color(0xFF9BC7C1)), borderRadius: BorderRadius.circular(30)), child: Text(tr(lang, '✦ Comunidade de Heliópolis, SP', '✦ Heliópolis Community, SP', '✦ Comunidad de Heliópolis, SP'), style: const TextStyle(color: _primary, fontWeight: FontWeight.w800, fontSize: 12))),
      const SizedBox(height: 28),
      Text(tr(lang, 'O artesanato\nde Heliópolis\npara o mundo.', 'The craftsmanship\nof Heliópolis\nfor the world.', 'La artesanía\nde Heliópolis\npara el mundo.'), style: TextStyle(fontSize: desktop ? 58 : 42, height: 1.03, fontWeight: FontWeight.w800, color: _fg, letterSpacing: -1.5)),
      const SizedBox(height: 24), Text(copy, style: TextStyle(color: _dim, fontSize: desktop ? 16 : 14, height: 1.65)),
      const SizedBox(height: 28), Row(children: [ElevatedButton.icon(onPressed: () => go(Page.products), icon: const Icon(Icons.shopping_bag_outlined), label: Text(tr(lang, 'Ver produtos', 'View products', 'Ver productos')), style: ElevatedButton.styleFrom(backgroundColor: _primary, foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16))), const SizedBox(width: 12), OutlinedButton(onPressed: () => go(Page.about), style: OutlinedButton.styleFrom(foregroundColor: _primary, side: const BorderSide(color: _primary), padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16)), child: Text(tr(lang, 'Conheça o projeto', 'Discover the project', 'Conoce el proyecto')))]),
    ]));
    final right = SizedBox(height: desktop ? 620 : 360, child: Image.asset(_heroImage, fit: BoxFit.cover, errorBuilder: (_, __, ___) => Container(color: _muted, alignment: Alignment.center, child: const Icon(Icons.image_not_supported_outlined, size: 60, color: _dim))));
    return desktop ? Row(crossAxisAlignment: CrossAxisAlignment.center, children: [Expanded(child: left), Expanded(child: right)]) : Column(children: [left, right]);
  }

  Widget _sectionTitle(String eyebrow, String title, {String? text}) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(eyebrow.toUpperCase(), style: const TextStyle(color: _primary, fontWeight: FontWeight.w800, letterSpacing: 1.4, fontSize: 12)), const SizedBox(height: 10), Text(title, style: const TextStyle(color: _fg, fontWeight: FontWeight.w800, fontSize: 38, height: 1.08)), if (text != null) ...[const SizedBox(height: 14), Text(text, style: const TextStyle(color: _dim, fontSize: 15, height: 1.65))]]);

  Widget _aboutHome() => Container(padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 80), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: LayoutBuilder(builder: (context, c) { final d = c.maxWidth > 800; final text = Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_sectionTitle(tr(lang, 'Quem Somos', 'About Us', 'Quiénes Somos'), tr(lang, 'Mulheres, histórias e oportunidades que começam em Heliópolis.', 'Women, stories and opportunities that begin in Heliópolis.', 'Mujeres, historias y oportunidades que comienzan en Heliópolis.')), const SizedBox(height: 18), Text(tr(lang, 'Conheça as mulheres que transformam técnicas, memórias e materiais em peças únicas. Cada criação nasce de uma trajetória, de saberes compartilhados e do desejo de construir novas possibilidades por meio do próprio trabalho.', 'Meet the women who turn techniques, memories and materials into unique pieces. Each creation grows from a personal journey, shared knowledge and the desire to build new possibilities through their work.', 'Conoce a las mujeres que transforman técnicas, memorias y materiales en piezas únicas. Cada creación nace de una trayectoria, saberes compartidos y el deseo de construir nuevas posibilidades a través de su trabajo.'), style: const TextStyle(color: _dim, height: 1.7, fontSize: 15)), const SizedBox(height: 14), Text(tr(lang, 'O projeto reúne catálogo, conteúdo e orientação em um só lugar, ajudando as artesãs a apresentar seu trabalho com autonomia e alcançar novos públicos.', 'The project brings together catalogue, content and guidance in one place, helping artisans present their work independently and reach new audiences.', 'El proyecto reúne catálogo, contenido y orientación en un solo lugar, ayudando a las artesanas a presentar su trabajo con autonomía y llegar a nuevos públicos.'), style: const TextStyle(color: _dim, height: 1.7, fontSize: 15))]); final image = ClipRRect(borderRadius: BorderRadius.circular(18), child: Image.network(_aboutImage, height: 380, width: double.infinity, fit: BoxFit.cover, errorBuilder: (_, __, ___) => Container(height: 380, color: _muted))); return d ? Row(crossAxisAlignment: CrossAxisAlignment.center, children: [Expanded(child: text), const SizedBox(width: 55), Expanded(child: image)]) : Column(children: [image, const SizedBox(height: 30), text]); }))));

  Widget _featured() => Container(color: const Color(0xFFFBF5E9), padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 72), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: _sectionTitle(tr(lang, 'Nossa loja', 'Our store', 'Nuestra tienda'), tr(lang, 'Peças com história.', 'Pieces with a story.', 'Piezas con historia.'))), TextButton(onPressed: () => go(Page.products), child: Text(tr(lang, 'Ver mais →', 'See more →', 'Ver más →'), style: const TextStyle(color: _primary, fontWeight: FontWeight.w800)))]), const SizedBox(height: 30), LayoutBuilder(builder: (_, c) { final count = c.maxWidth > 900 ? 3 : c.maxWidth > 600 ? 2 : 1; return GridView.builder(shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), itemCount: 3, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: count, crossAxisSpacing: 18, mainAxisSpacing: 18, childAspectRatio: .76), itemBuilder: (_, i) => _productCard(i)); })]))));

  Widget _productCard(int i) { final p = _products[i]; return Card(color: _card, elevation: 0, clipBehavior: Clip.antiAlias, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14), side: const BorderSide(color: _border)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Stack(children: [Positioned.fill(child: Image.network(p['image']!, fit: BoxFit.cover, errorBuilder: (_, __, ___) => Container(color: _muted, alignment: Alignment.center, child: const Icon(Icons.image_outlined, size: 45)))), Positioned(top: 10, right: 10, child: CircleAvatar(backgroundColor: Colors.white.withValues(alpha: .92), child: IconButton(iconSize: 18, onPressed: () => setState(() { favorites.contains(i) ? favorites.remove(i) : favorites.add(i); }), icon: Icon(favorites.contains(i) ? Icons.favorite : Icons.favorite_border, color: favorites.contains(i) ? _accent : _fg))) )])), Padding(padding: const EdgeInsets.all(15), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(p['category']!.toUpperCase(), style: const TextStyle(color: _primary, fontWeight: FontWeight.w800, fontSize: 10, letterSpacing: 1)), const SizedBox(height: 5), Text(p['name']!, style: const TextStyle(color: _fg, fontWeight: FontWeight.w800, fontSize: 19)), const SizedBox(height: 4), Text('${tr(lang, 'por', 'by', 'por')} ${p['artisan']}', style: const TextStyle(color: _dim, fontSize: 12)), const SizedBox(height: 8), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(p['price']!, style: const TextStyle(fontWeight: FontWeight.w800, color: _fg)), TextButton(onPressed: addCart, child: Text(tr(lang, 'Comprar', 'Buy', 'Comprar')))])]))])); }

  Widget _how() { final items = [tr(lang, 'Peças feitas à mão', 'Handmade pieces', 'Piezas hechas a mano'), tr(lang, 'Histórias que conectam', 'Stories that connect', 'Historias que conectan'), tr(lang, 'Compra direta', 'Buy directly', 'Compra directa'), tr(lang, 'Impacto na comunidade', 'Community impact', 'Impacto en la comunidad')]; return Container(padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 80), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_sectionTitle(tr(lang, 'Como funciona', 'How it works', 'Cómo funciona'), tr(lang, 'Do feito à mão para o mundo.', 'From handmade to the world.', 'De lo hecho a mano al mundo.')), const SizedBox(height: 30), LayoutBuilder(builder: (_, c) { final n = c.maxWidth > 900 ? 4 : c.maxWidth > 550 ? 2 : 1; return GridView.builder(shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), itemCount: 4, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: n, crossAxisSpacing: 15, mainAxisSpacing: 15, childAspectRatio: 1.05), itemBuilder: (_, i) => Container(padding: const EdgeInsets.all(22), decoration: BoxDecoration(color: _card, border: Border.all(color: _border), borderRadius: BorderRadius.circular(14)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('0${i + 1}', style: const TextStyle(color: _primary, fontWeight: FontWeight.w900, fontSize: 13)), const SizedBox(height: 25), Text(items[i], style: const TextStyle(color: _fg, fontWeight: FontWeight.w800, fontSize: 18)), const SizedBox(height: 10), Text(tr(lang, ['Encontre produtos únicos feitos com cuidado por mulheres artesãs.', 'Conheça técnicas, histórias e referências culturais.', 'Escolha sua peça e compre pela plataforma.', 'Sua compra fortalece renda e trabalho na comunidade.'][i], ['Find unique products carefully made by women artisans.', 'Learn techniques, stories and cultural references.', 'Choose your piece and buy through the platform.', 'Your purchase strengthens income and work in the community.'][i], ['Encuentra productos únicos hechos por mujeres artesanas.', 'Conoce técnicas, historias y referencias culturales.', 'Elige tu pieza y compra en la plataforma.', 'Tu compra fortalece los ingresos y el trabajo comunitario.'][i]), style: const TextStyle(color: _dim, fontSize: 13, height: 1.5))]))); })])))); }

  Widget _signup() => Container(color: _primary, padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 70), child: Center(child: Column(children: [Text(tr(lang, 'Pronta para fazer parte?', 'Ready to be part of it?', '¿Lista para ser parte?'), textAlign: TextAlign.center, style: const TextStyle(color: Colors.white, fontSize: 38, fontWeight: FontWeight.w800)), const SizedBox(height: 12), Text(tr(lang, 'Cadastre-se para comprar ou apresentar sua arte ao mundo.', 'Sign up to shop or present your art to the world.', 'Regístrate para comprar o presentar tu arte al mundo.'), textAlign: TextAlign.center, style: const TextStyle(color: Colors.white70, fontSize: 15)), const SizedBox(height: 25), Wrap(spacing: 12, children: [ElevatedButton(onPressed: () => go(Page.accountSignup), style: ElevatedButton.styleFrom(backgroundColor: Colors.white, foregroundColor: _primary), child: Text(tr(lang, 'Criar uma conta', 'Create an account', 'Crear una cuenta'))), OutlinedButton(onPressed: () => go(Page.artisanSignup), style: OutlinedButton.styleFrom(foregroundColor: Colors.white, side: const BorderSide(color: Colors.white)), child: Text(tr(lang, 'Quero ser artesã', 'I want to be an artisan', 'Quiero ser artesana')))])])));

  Widget _footer() => Container(color: const Color(0xFFFBF5E9), padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 55), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Column(children: [Wrap(alignment: WrapAlignment.spaceBetween, runSpacing: 30, spacing: 60, children: [SizedBox(width: 240, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Image.asset('assets/image/logo-mulheres-artesas-heliopolis.png', width: 170), const SizedBox(height: 12), Text(tr(lang, 'Conectando o talento artesanal de Heliópolis com o mercado mundial.', 'Connecting Heliópolis artisan talent with the global market.', 'Conectando el talento artesanal de Heliópolis con el mercado mundial.'), style: const TextStyle(color: _dim, height: 1.5, fontSize: 13))])), _footerCol(tr(lang, 'Plataforma', 'Platform', 'Plataforma'), ['Como Funciona', 'Catálogo', 'Guia de Exportação', 'Mercados']), _footerCol(tr(lang, 'Suporte', 'Support', 'Soporte'), ['Central de Ajuda', 'WhatsApp', 'Documentação', 'Parceiros']), _footerCol(tr(lang, 'Comunidade', 'Community', 'Comunidad'), ['Sobre Heliópolis', 'Histórias de Sucesso', 'Eventos', 'Blog'])]), const SizedBox(height: 35), const Divider(color: _border), const SizedBox(height: 15), Wrap(alignment: WrapAlignment.center, spacing: 18, children: [TextButton(onPressed: () { legalDoc = LegalDoc.terms; go(Page.legal); }, child: const Text('Termos')), TextButton(onPressed: () { legalDoc = LegalDoc.privacy; go(Page.legal); }, child: const Text('Privacidade')), TextButton(onPressed: () { legalDoc = LegalDoc.cookies; go(Page.legal); }, child: const Text('Cookies')), TextButton(onPressed: () { legalDoc = LegalDoc.commerce; go(Page.legal); }, child: const Text('Compras, Trocas e Vendas')), TextButton(onPressed: () { legalDoc = LegalDoc.community; go(Page.legal); }, child: const Text('Comunidade'))]), const SizedBox(height: 8), Text('© 2026 Artesãs de Heliópolis Global · Parceria com Sebrae SP e APEX-Brasil · Heliópolis, São Paulo, Brasil', textAlign: TextAlign.center, style: const TextStyle(color: _dim, fontSize: 11))]))));
  Widget _footerCol(String title, List<String> links) => SizedBox(width: 160, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(fontWeight: FontWeight.w800, color: _fg)), const SizedBox(height: 10), ...links.map((x) => TextButton(onPressed: () => _footerAction(x), style: TextButton.styleFrom(padding: EdgeInsets.zero, alignment: Alignment.centerLeft), child: Text(x, style: const TextStyle(color: _dim, fontSize: 12))))]));
  void _footerAction(String x) { if (x == 'Catálogo') go(Page.products); else if (x == 'Sobre Heliópolis') go(Page.about); else if (x == 'Guia de Exportação') go(Page.artisanSignup); else if (x == 'Central de Ajuda') { artisanSection = ArtisanSection.help; go(Page.artisan); } }

  Widget _about() => SingleChildScrollView(padding: const EdgeInsets.all(28), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1000), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SizedBox(height: 55), _sectionTitle(tr(lang, 'Nossa história', 'Our story', 'Nuestra historia'), tr(lang, 'Mulheres, histórias e oportunidades que começam em Heliópolis.', 'Women, stories and opportunities that begin in Heliópolis.', 'Mujeres, historias y oportunidades que comienzan en Heliópolis.')), const SizedBox(height: 25), Text(tr(lang, 'O projeto nasceu para aproximar o trabalho das mulheres artesãs de Heliópolis de novos públicos, valorizando saberes, histórias e produtos feitos à mão.', 'The project was created to connect the work of women artisans from Heliópolis with new audiences, valuing knowledge, stories and handmade products.', 'El proyecto nació para acercar el trabajo de las mujeres artesanas de Heliópolis a nuevos públicos, valorando conocimientos, historias y productos hechos a mano.'), style: const TextStyle(color: _dim, height: 1.8, fontSize: 16)), const SizedBox(height: 20), Text(tr(lang, 'A plataforma reúne vitrine digital, orientação para exportação, comunicação e ferramentas para ajudar as artesãs a alcançar mercados nacionais e internacionais.', 'The platform brings together a digital showcase, export guidance, communication and tools to help artisans reach national and international markets.', 'La plataforma reúne escaparate digital, orientación para exportación, comunicación y herramientas para ayudar a las artesanas a alcanzar mercados nacionales e internacionales.'), style: const TextStyle(color: _dim, height: 1.8, fontSize: 16)), const SizedBox(height: 35), Wrap(spacing: 15, runSpacing: 15, children: ['VALORIZAR', 'CONECTAR', 'TRANSFORMAR'].map((x) => Container(width: 280, padding: const EdgeInsets.all(22), decoration: BoxDecoration(color: _card, border: Border.all(color: _border), borderRadius: BorderRadius.circular(14)), child: Text(x, style: const TextStyle(color: _primary, fontWeight: FontWeight.w900, letterSpacing: 1.3)))).toList()), const SizedBox(height: 70)]))));

  Widget _catalog() { final cats = ['Todos', 'Acessórios', 'Joias', 'Casa', 'Vestuário', 'Brinquedos']; final list = category == 'Todos' ? List.generate(_products.length, (i) => i) : List.generate(_products.length, (i) => i).where((i) => _products[i]['category'] == category).toList(); return SingleChildScrollView(padding: const EdgeInsets.all(28), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SizedBox(height: 40), _sectionTitle(tr(lang, 'Catálogo', 'Catalogue', 'Catálogo'), tr(lang, 'Feito à mão, com propósito.', 'Handmade, with purpose.', 'Hecho a mano, con propósito.')), const SizedBox(height: 25), Wrap(spacing: 8, runSpacing: 8, children: cats.map((c) => ChoiceChip(label: Text(c), selected: category == c, onSelected: (_) => setState(() => category = c), selectedColor: _primary, labelStyle: TextStyle(color: category == c ? Colors.white : _fg))).toList()), const SizedBox(height: 30), LayoutBuilder(builder: (_, c) { final n = c.maxWidth > 950 ? 3 : c.maxWidth > 600 ? 2 : 1; return GridView.builder(shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), itemCount: list.length, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: n, crossAxisSpacing: 18, mainAxisSpacing: 18, childAspectRatio: .76), itemBuilder: (_, j) => _productCard(list[j])); })])))); }

  Widget _login() => _formPage(title: tr(lang, 'Minha conta', 'My account', 'Mi cuenta'), subtitle: tr(lang, 'Entre para acompanhar compras ou gerenciar seu perfil de artesã.', 'Sign in to manage purchases or your artisan profile.', 'Inicia sesión para gestionar compras o tu perfil de artesana.'), fields: ['E-mail', 'Senha'], button: tr(lang, 'Entrar', 'Sign in', 'Entrar'), footer: Row(mainAxisAlignment: MainAxisAlignment.center, children: [const Text('Ainda não tem conta?'), TextButton(onPressed: () => go(Page.accountSignup), child: Text(tr(lang, 'Criar conta', 'Create account', 'Crear cuenta')))]), onSubmit: () { signedIn = true; role = 'buyer'; go(Page.buyer); });

  Widget _accountSignup() => _formPage(title: tr(lang, 'Crie sua conta', 'Create your account', 'Crea tu cuenta'), subtitle: tr(lang, 'Cadastre-se para comprar, favoritar produtos e acompanhar pedidos.', 'Sign up to shop, favorite products and track orders.', 'Regístrate para comprar, guardar favoritos y seguir pedidos.'), fields: ['Nome', 'E-mail', 'Senha', 'Confirmar senha'], button: tr(lang, 'Criar minha conta', 'Create my account', 'Crear mi cuenta'), footer: TextButton(onPressed: () => go(Page.login), child: Text(tr(lang, 'Já tenho uma conta', 'I already have an account', 'Ya tengo una cuenta'))), onSubmit: () { signedIn = true; role = 'buyer'; go(Page.buyer); });

  Widget _artisanSignup() => _formPage(title: tr(lang, 'Inscreva-se no programa exclusivo', 'Apply to the exclusive program', 'Inscríbete en el programa exclusivo'), subtitle: tr(lang, 'Somente para mulheres artesãs de Heliópolis. Nossa equipe entra em contato após o cadastro.', 'Only for women artisans from Heliópolis. Our team will contact you after registration.', 'Solo para mujeres artesanas de Heliópolis. Nuestro equipo se pondrá en contacto tras el registro.'), fields: ['Nome', 'WhatsApp', 'E-mail', 'Instagram', 'Endereço', 'Produto principal'], button: tr(lang, 'Inscrever', 'Apply', 'Inscribirme'), footer: TextButton(onPressed: () => go(Page.home), child: Text(tr(lang, 'Voltar para o início', 'Back to home', 'Volver al inicio'))), onSubmit: () { signedIn = true; role = 'artisan'; artisanSection = ArtisanSection.overview; _snack(tr(lang, 'Cadastro recebido! Nossa equipe entrará em contato.', 'Registration received! Our team will contact you.', '¡Registro recibido! Nuestro equipo se pondrá en contacto.')); go(Page.artisan); });

  Widget _formPage({required String title, required String subtitle, required List<String> fields, required String button, required Widget footer, required VoidCallback onSubmit}) => SingleChildScrollView(padding: const EdgeInsets.all(28), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 560), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SizedBox(height: 55), Text(title, style: const TextStyle(fontSize: 42, height: 1.05, fontWeight: FontWeight.w800, color: _fg)), const SizedBox(height: 14), Text(subtitle, style: const TextStyle(color: _dim, fontSize: 15, height: 1.6)), const SizedBox(height: 30), ...fields.map((f) => Padding(padding: const EdgeInsets.only(bottom: 15), child: TextFormField(obscureText: f.toLowerCase().contains('senha'), decoration: InputDecoration(labelText: f, filled: true, fillColor: _card, border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: const BorderSide(color: _border)), enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: const BorderSide(color: _border)))))), const SizedBox(height: 8), SizedBox(width: double.infinity, child: ElevatedButton(onPressed: onSubmit, style: ElevatedButton.styleFrom(backgroundColor: _primary, foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(vertical: 17)), child: Text(button))), const SizedBox(height: 15), Center(child: footer), const SizedBox(height: 80)]))));

  Widget _buyer() => SingleChildScrollView(padding: const EdgeInsets.all(28), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1050), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SizedBox(height: 35), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.center, children: [Flexible(child: Text(tr(lang, 'Minha conta', 'My account', 'Mi cuenta'), style: const TextStyle(fontSize: 38, fontWeight: FontWeight.w800, color: _fg))), TextButton.icon(onPressed: () { signedIn = false; role = 'buyer'; go(Page.home); }, icon: const Icon(Icons.logout), label: Text(tr(lang, 'Sair', 'Sign out', 'Salir')))]), const SizedBox(height: 25), Wrap(spacing: 12, runSpacing: 12, children: [_accountTile(Icons.receipt_long_outlined, tr(lang, 'Meus pedidos', 'My orders', 'Mis pedidos'), '2'), _accountTile(Icons.shopping_cart_outlined, 'Carrinho', '$_cartCountLabel'), _accountTile(Icons.favorite_border, tr(lang, 'Favoritos', 'Favorites', 'Favoritos'), '${favorites.length}'), _accountTile(Icons.settings_outlined, tr(lang, 'Configurações', 'Settings', 'Configuración'), '')]), const SizedBox(height: 35), Container(padding: const EdgeInsets.all(24), decoration: BoxDecoration(color: _card, border: Border.all(color: _border), borderRadius: BorderRadius.circular(14)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(tr(lang, 'Seus próximos passos', 'Your next steps', 'Tus próximos pasos'), style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w800, color: _fg)), const SizedBox(height: 10), Text(tr(lang, 'Explore o catálogo, salve seus favoritos e acompanhe suas compras por aqui.', 'Explore the catalogue, save favorites and track your purchases here.', 'Explora el catálogo, guarda favoritos y sigue tus compras aquí.'), style: const TextStyle(color: _dim, height: 1.6)), const SizedBox(height: 15), ElevatedButton(onPressed: () => go(Page.products), child: Text(tr(lang, 'Ir para a loja', 'Go to store', 'Ir a la tienda')))]))]))));
  String get _cartCountLabel => '$cart';
  Widget _accountTile(IconData icon, String title, String value) => Container(width: 235, padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: _card, border: Border.all(color: _border), borderRadius: BorderRadius.circular(12)), child: Row(children: [Icon(icon, color: _primary), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(fontWeight: FontWeight.w800, color: _fg)), if (value.isNotEmpty) Text(value, style: const TextStyle(color: _dim, fontSize: 12))]))]));

  Widget _artisan() { final items = {'Visão geral': ArtisanSection.overview, 'Pedidos': ArtisanSection.orders, 'Mensagens': ArtisanSection.messages, 'Minha vitrine': ArtisanSection.products, 'Vendas': ArtisanSection.sales, 'Alcançar o mundo': ArtisanSection.export, 'Ajuda': ArtisanSection.help, 'Configurações': ArtisanSection.settings}; return Scaffold(backgroundColor: _bg, body: Row(children: [if (MediaQuery.sizeOf(context).width > 850) Container(width: 260, color: const Color(0xFFFBF5E9), padding: const EdgeInsets.fromLTRB(20, 35, 20, 20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Image.asset('assets/image/logo-mulheres-artesas-heliopolis.png', width: 170), const SizedBox(height: 35), const Text('Bem-vinda de volta,', style: TextStyle(color: _dim)), const Text('Maria!', style: TextStyle(fontSize: 25, fontWeight: FontWeight.w900, color: _fg)), const SizedBox(height: 30), Expanded(child: ListView(children: items.entries.map((e) => _side(e.key, e.value)).toList())), TextButton.icon(onPressed: () => go(Page.home), icon: const Icon(Icons.logout), label: const Text('Sair da conta'))])), Expanded(child: SingleChildScrollView(padding: const EdgeInsets.fromLTRB(28, 30, 28, 70), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1000), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_artisanTop(), _artisanContent()])))))])); }
  Widget _side(String label, ArtisanSection s) => ListTile(selected: artisanSection == s, selectedTileColor: const Color(0xFFE2F0EC), leading: const Icon(Icons.circle_outlined, size: 17), title: Text(label), onTap: () => setState(() => artisanSection = s));
  Widget _artisanTop() {
    final title = Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(_sectionLabel(), style: const TextStyle(color: _primary, fontSize: 11, fontWeight: FontWeight.w900, letterSpacing: 1.2)), const SizedBox(height: 6), Text(_sectionTitleArtisan(), style: const TextStyle(fontSize: 35, fontWeight: FontWeight.w800, color: _fg))]);
    final actions = Wrap(spacing: 8, runSpacing: 8, children: [OutlinedButton.icon(onPressed: () => setState(() => artisanSection = ArtisanSection.export), icon: const Icon(Icons.public), label: const Text('Exportação')), ElevatedButton.icon(onPressed: () => _snack('Produto salvo!'), icon: const Icon(Icons.add), label: const Text('Adicionar produto'))]);
    return LayoutBuilder(builder: (_, c) => c.maxWidth < 620
      ? Column(crossAxisAlignment: CrossAxisAlignment.start, children: [title, const SizedBox(height: 16), actions])
      : Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Flexible(child: title), const SizedBox(width: 16), actions]));
  }
  String _sectionLabel() => artisanSection == ArtisanSection.overview ? 'UM BOM DIA PARA CRIAR' : 'PAINEL DA ARTESÃ';
  String _sectionTitleArtisan() => {ArtisanSection.overview:'Olá, Maria!', ArtisanSection.orders:'Pedidos', ArtisanSection.messages:'Mensagens', ArtisanSection.products:'Minha vitrine', ArtisanSection.sales:'Vendas', ArtisanSection.export:'Alcançar o mundo', ArtisanSection.help:'Ajuda e suporte', ArtisanSection.settings:'Configurações'}[artisanSection] ?? 'Painel';

  Widget _artisanContent() { switch (artisanSection) { case ArtisanSection.overview: return _artisanOverview(); case ArtisanSection.orders: return _artisanOrders(); case ArtisanSection.messages: return _artisanMessages(); case ArtisanSection.products: return _artisanProducts(); case ArtisanSection.sales: return _artisanSales(); case ArtisanSection.export: return _artisanExport(); case ArtisanSection.help: return _artisanHelp(); case ArtisanSection.settings: return _artisanSettings(); } }
  Widget _artisanOverview() => Column(children: [const SizedBox(height: 25), Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: const Color(0xFFE6F0EA), borderRadius: BorderRadius.circular(13)), child: const Row(children: [Icon(Icons.public, color: _primary), SizedBox(width: 14), Expanded(child: Text('Seu feito à mão pode cruzar fronteiras. Conte a história da sua peça. A gente ajuda com idioma, frete e os próximos passos.', style: TextStyle(color: _fg, height: 1.5)))])), const SizedBox(height: 20), Wrap(spacing: 12, runSpacing: 12, children: [_stat('Produtos ativos', '12', '+2 este mês', ArtisanSection.products), _stat('Pedidos', '4', '2 aguardando envio', ArtisanSection.orders), _stat('Vendas no mês', 'R\$ 1.240', '+18% que no mês passado', ArtisanSection.sales), _stat('Mensagens', '2', 'de compradores', ArtisanSection.messages)]), const SizedBox(height: 30), _panel('Pedidos recentes', _orderList())]);
  Widget _stat(String a, String b, String c, ArtisanSection target) => InkWell(onTap: () => setState(() => artisanSection = target), child: Container(width: 220, padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: _card, border: Border.all(color: _border), borderRadius: BorderRadius.circular(12)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(a, style: const TextStyle(color: _dim, fontSize: 12)), const SizedBox(height: 8), Text(b, style: const TextStyle(color: _fg, fontWeight: FontWeight.w900, fontSize: 25)), const SizedBox(height: 5), Text(c, style: const TextStyle(color: _primary, fontSize: 11, fontWeight: FontWeight.w700))])));
  Widget _panel(String title, Widget child) => Container(width: double.infinity, padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: _card, border: Border.all(color: _border), borderRadius: BorderRadius.circular(13)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(color: _fg, fontSize: 21, fontWeight: FontWeight.w800)), const SizedBox(height: 12), child]));
  Widget _orderList() => Column(children: [['#HLP-2408', 'Cesta Trançada Sol', 'Ana Clara', 'R\$ 85'], ['#HLP-2397', 'Colar Raízes', 'Camila M.', 'R\$ 120'], ['#HLP-2379', 'Boneca Abayomi', 'Sofia R.', 'R\$ 95'], ['#HLP-2364', 'Kit Casa', 'Marina L.', 'R\$ 210']].map((o) => ListTile(leading: CircleAvatar(backgroundColor: const Color(0xFFE2F0EC), child: const Icon(Icons.shopping_bag_outlined, color: _primary, size: 19)), title: Text(o[1], style: const TextStyle(fontWeight: FontWeight.w800)), subtitle: Text('${o[0]} · ${o[2]}'), trailing: Text(o[3], style: const TextStyle(fontWeight: FontWeight.w800)))).toList());
  Widget _artisanOrders() => _panel('Pedidos', _orderList());
  Widget _artisanMessages() => _panel('Mensagens', Column(children: [['Camila M.', 'Dúvida sobre o prazo', 'Olá, Maria! Você consegue enviar o Colar Raízes ainda esta semana?'], ['Ana Clara', 'Pedido #HLP-2408', 'Estou ansiosa para receber minha cesta. Obrigada pelo cuidado!'], ['Equipe Artesãs', 'Sua vitrine está linda', 'Uma dica: fotos com luz natural recebem mais visitas.']].map((m) => ListTile(leading: CircleAvatar(child: Text(m[0][0])), title: Text(m[1], style: const TextStyle(fontWeight: FontWeight.w800)), subtitle: Text(m[2]), trailing: const Icon(Icons.chevron_right))).toList()));
  Widget _artisanProducts() => Column(children: [_panel('Minha vitrine', LayoutBuilder(builder: (_, c) { final n = c.maxWidth > 700 ? 3 : c.maxWidth > 420 ? 2 : 1; return GridView.count(shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), crossAxisCount: n, crossAxisSpacing: 14, mainAxisSpacing: 14, childAspectRatio: .75, children: _products.take(4).map((p) => Card(color: _card, elevation: 0, clipBehavior: Clip.antiAlias, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Image.network(p['image']!, width: double.infinity, fit: BoxFit.cover, errorBuilder: (_, __, ___) => Container(color: _muted))), Padding(padding: const EdgeInsets.all(12), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(p['category']!, style: const TextStyle(color: _primary, fontSize: 10, fontWeight: FontWeight.w800)), Text(p['name']!, style: const TextStyle(fontSize: 17, fontWeight: FontWeight.w800)), Text(p['price']!, style: const TextStyle(color: _dim)), const SizedBox(height: 5), OutlinedButton(onPressed: () => _snack('Edição de produto em breve — seu produto já está salvo.'), child: const Text('Editar produto'))]))]))).toList()); }))]);
  Widget _artisanSales() => Column(children: [_panel('Vendas no mês', const SizedBox(height: 190, child: Center(child: Icon(Icons.show_chart, size: 80, color: _primary)))), const SizedBox(height: 15), _panel('Resumo', const Column(children: [ListTile(title: Text('Receita'), trailing: Text('R\$ 1.240')), ListTile(title: Text('Pedidos concluídos'), trailing: Text('8')), ListTile(title: Text('Ticket médio'), trailing: Text('R\$ 155'))]))]);
  Widget _artisanExport() => _panel('Alcançar o mundo', Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Seu produto pode chegar a compradores internacionais. Organize fotos, descrição, materiais, custos e documentação.', style: TextStyle(color: _dim, height: 1.6)), const SizedBox(height: 20), ...['1. Prepare sua vitrine', '2. Calcule custos e frete', '3. Revise documentação', '4. Escolha mercados', '5. Converse com compradores'].map((x) => ListTile(leading: const CircleAvatar(backgroundColor: Color(0xFFE2F0EC), child: Icon(Icons.check, color: _primary, size: 17)), title: Text(x, style: const TextStyle(fontWeight: FontWeight.w700))))]));
  Widget _artisanHelp() => _panel('Ajuda e suporte', Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Encontre respostas para dúvidas sobre cadastro, produtos, pedidos e exportação.', style: TextStyle(color: _dim, height: 1.6)), const SizedBox(height: 15), ...['Como cadastrar um produto?', 'Como acompanhar um pedido?', 'Como preparar uma exportação?', 'Como falar com o suporte?'].map((x) => ExpansionTile(title: Text(x), children: [const Padding(padding: EdgeInsets.all(15), child: Text('Nossa equipe pode orientar você pelo canal de suporte da plataforma.'))]))]));
  Widget _artisanSettings() => _panel('Configurações', Column(children: [SwitchListTile(value: true, onChanged: (_) {}, title: const Text('Receber mensagens de compradores')), SwitchListTile(value: true, onChanged: (_) {}, title: const Text('Receber avisos de pedidos')), ListTile(title: const Text('Idioma'), trailing: Text(lang == Lang.pt ? 'Português' : lang == Lang.en ? 'English' : 'Español'))]));

  Widget _legal() { final data = {LegalDoc.terms: ['Termos de Uso', 'DOCUMENTO DA PLATAFORMA', 'Estes termos definem as regras para usar a plataforma, comprar produtos e participar do programa de artesãs.'], LegalDoc.privacy: ['Política de Privacidade', 'PROTEÇÃO DE DADOS', 'Este documento explica quais dados são usados para criar contas, processar pedidos, oferecer suporte e manter a segurança da plataforma.'], LegalDoc.cookies: ['Política de Cookies', 'TRANSPARÊNCIA DIGITAL', 'Cookies e tecnologias semelhantes ajudam a manter a sessão, lembrar preferências e entender como a plataforma é utilizada.'], LegalDoc.commerce: ['Compras, Trocas e Vendas', 'REGRAS DA EXPERIÊNCIA', 'Regras claras ajudam compradores e artesãs a negociar com segurança e previsibilidade.'], LegalDoc.community: ['Diretrizes da Comunidade', 'CONVIVÊNCIA E RESPEITO', 'A plataforma existe para valorizar o trabalho das artesãs e promover relações comerciais respeitosas.']}[legalDoc]!; return SingleChildScrollView(padding: const EdgeInsets.all(28), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 820), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SizedBox(height: 45), TextButton.icon(onPressed: () => go(Page.home), icon: const Icon(Icons.arrow_back), label: const Text('Voltar')), const SizedBox(height: 30), Text(data[1], style: const TextStyle(color: _primary, fontWeight: FontWeight.w900, letterSpacing: 1.3)), const SizedBox(height: 12), Text(data[0], style: const TextStyle(color: _fg, fontSize: 45, fontWeight: FontWeight.w800)), const SizedBox(height: 15), Text(data[2], style: const TextStyle(color: _dim, height: 1.7, fontSize: 15)), const SizedBox(height: 30), ..._legalSections(legalDoc).map((x) => Container(width: double.infinity, margin: const EdgeInsets.only(bottom: 12), padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: _card, border: Border.all(color: _border), borderRadius: BorderRadius.circular(12)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(x.$1, style: const TextStyle(color: _fg, fontWeight: FontWeight.w800, fontSize: 18)), const SizedBox(height: 7), Text(x.$2, style: const TextStyle(color: _dim, height: 1.65))]))), const SizedBox(height: 50)])))); }
  List<(String,String)> _legalSections(LegalDoc d) => {LegalDoc.terms: [('Uso da plataforma', 'A plataforma conecta compradores e artesãs. Cada pessoa deve fornecer informações verdadeiras, proteger suas credenciais e usar o serviço de forma legal e respeitosa.'), ('Compras e pagamentos', 'Os detalhes de preço, prazo, disponibilidade, entrega, troca e reembolso devem ser apresentados antes da confirmação.'), ('Conteúdo e responsabilidade', 'Cada artesã é responsável por seus produtos, descrições, fotos e informações publicadas.')], LegalDoc.privacy: [('Dados coletados', 'Podemos tratar nome, e-mail, telefone, endereço e dados necessários para o cadastro e atendimento.'), ('Finalidades', 'Usamos os dados para autenticar contas, processar compras, acompanhar entregas e responder solicitações.'), ('Direitos', 'Você pode solicitar confirmação, acesso, correção, atualização ou exclusão dos seus dados, observadas as hipóteses legais.')], LegalDoc.cookies: [('Cookies necessários', 'São usados para segurança, funcionamento do login, carrinho e navegação.'), ('Preferências e métricas', 'Preferências de idioma e métricas agregadas podem ser usadas para melhorar a experiência.'), ('Controle', 'Você pode bloquear ou apagar cookies nas configurações do navegador.')], LegalDoc.commerce: [('Pedido e confirmação', 'O comprador deve revisar itens, endereço, frete e valor total antes de finalizar.'), ('Envio e acompanhamento', 'A artesã atualiza o status do pedido e informa o envio.'), ('Troca e reembolso', 'Solicitações serão analisadas conforme a legislação brasileira aplicável e as condições do produto.')], LegalDoc.community: [('Respeito', 'Não são permitidos assédio, discriminação, ameaças, conteúdo ilegal ou tentativas de constranger outros usuários.'), ('Autenticidade', 'Produtos, histórias, fotos e avaliações devem ser verdadeiros.'), ('Moderação', 'Podemos remover conteúdo e suspender acessos quando houver violação das diretrizes.')] }[d]!;
}
